@echo off
REM ChatMode Auto-Installer for Windows
REM This script automatically installs ChatMode with conda environment

setlocal EnableDelayedExpansion

echo ============================================
echo     ChatMode Auto-Installer v2.0
echo     AI Agent Orchestration System
echo ============================================
echo.

REM Check if conda is installed
where conda >nul 2>nul
if %errorlevel% neq 0 (
    echo [ERROR] Conda is not installed!
    echo Please install Miniconda or Anaconda first:
    echo   - Miniconda: https://docs.conda.io/en/latest/miniconda.html
    pause
    exit /b 1
)

echo [INFO] Conda found
echo.

REM Set variables
set "CONDA_ENV_NAME=chatmode"
set "PROJECT_DIR=%CD%"
set "DEFAULT_PORT=8002"

echo [INFO] Setting up conda environment: %CONDA_ENV_NAME%

REM Check if environment exists
conda env list | findstr /C:"%CONDA_ENV_NAME% " >nul
if %errorlevel% equ 0 (
    echo [WARNING] Conda environment '%CONDA_ENV_NAME%' already exists
    set /p RECREATE="Do you want to recreate it? (y/N): "
    if /I "!RECREATE!"=="y" (
        echo [INFO] Removing existing environment...
        call conda env remove -n %CONDA_ENV_NAME% -y
    ) else (
        echo [INFO] Using existing environment
        goto :SETUP_DIRS
    )
)

echo [INFO] Creating conda environment from environment.yml...
call conda env create -f environment.yml
if %errorlevel% neq 0 (
    echo [ERROR] Failed to create conda environment
    pause
    exit /b 1
)

echo [SUCCESS] Conda environment created

:SETUP_DIRS
echo.
echo [INFO] Creating required directories...
if not exist "data\chroma" mkdir "data\chroma"
if not exist "tts_out" mkdir "tts_out"
if not exist "logs" mkdir "logs"
echo [SUCCESS] Directories created

echo.
echo [INFO] Installing additional dependencies...
call conda activate %CONDA_ENV_NAME%
pip install "bcrypt>=4.0.0,<4.1.0" passlib==1.7.4
echo [SUCCESS] Dependencies installed

echo.
echo [INFO] Setting up environment configuration...
if not exist ".env" (
    if exist ".env.example" (
        copy .env.example .env
        echo [SUCCESS] Created .env from .env.example
        echo [WARNING] Please edit .env with your API keys and settings
    ) else (
        echo [WARNING] No .env.example found, creating minimal .env
        (
            echo # ChatMode Configuration
            echo # LLM Provider
            echo OPENAI_API_KEY=ollama
            echo OPENAI_BASE_URL=http://localhost:11434
            echo OLLAMA_BASE_URL=http://localhost:11434
            echo.
            echo # Embeddings
            echo EMBEDDING_PROVIDER=ollama
            echo EMBEDDING_MODEL=nomic-embed-text
            echo EMBEDDING_BASE_URL=http://localhost:11434
            echo.
            echo # Storage
            echo CHROMA_DIR=./data/chroma
            echo DATABASE_URL=sqlite:///./data/chatmode.db
            echo.
            echo # TTS ^(disabled by default^)
            echo TTS_ENABLED=false
            echo.
            echo # Security
            echo SECRET_KEY=change-this-in-production
            echo ALLOWED_ORIGINS=*
            echo.
            echo # Conversation Settings
            echo MAX_CONTEXT_TOKENS=32000
            echo MAX_OUTPUT_TOKENS=512
            echo TEMPERATURE=0.9
        ) > .env
        echo [SUCCESS] Created minimal .env file
    )
) else (
    echo [INFO] .env file already exists, skipping
)

echo.
echo [INFO] Initializing database...
call conda activate %CONDA_ENV_NAME%
python bootstrap_admin.py
if %errorlevel% neq 0 (
    echo [ERROR] Database initialization failed
    pause
    exit /b 1
)
echo [SUCCESS] Database initialized

echo.
echo [INFO] Verifying agent configuration...
if not exist "agent_config.json" (
    echo [WARNING] agent_config.json not found, creating default...
    (
        echo {
        echo   "agents": [
        echo     {
        echo       "name": "lawyer",
        echo       "file": "profiles/lawyer.json"
        echo     },
        echo     {
        echo       "name": "crook",
        echo       "file": "profiles/crook.json"
        echo     }
        echo   ]
        echo }
    ) > agent_config.json
    echo [SUCCESS] Created default agent_config.json
) else (
    echo [SUCCESS] agent_config.json found
)

echo.
echo [INFO] Creating launcher script...
(
    echo @echo off
    echo REM ChatMode Launcher Script
    echo REM Auto-generated by autoinstall.bat
    echo.
    echo cd /d "%PROJECT_DIR%"
    echo call conda activate %CONDA_ENV_NAME%
    echo.
    echo echo ============================================
    echo echo     ChatMode Server Launcher
    echo echo ============================================
    echo echo.
    echo echo Starting server on http://localhost:%DEFAULT_PORT%
    echo echo Default login: admin / admin
    echo echo.
    echo echo Press Ctrl+C to stop
    echo echo.
    echo.
    echo python -m uvicorn web_admin:app --host 0.0.0.0 --port %DEFAULT_PORT% --reload
    echo.
    echo pause
) > start.bat
echo [SUCCESS] Created start.bat launcher

echo.
echo ============================================
echo     Installation Complete!
echo ============================================
echo.
echo Quick Start:
echo   1. Edit .env file with your API keys
echo   2. Start the server: start.bat
echo   3. Open browser: http://localhost:%DEFAULT_PORT%
echo   4. Login with: admin / admin
echo.
echo Note: Make sure Ollama is running if using local models
echo.

set /p START_NOW="Would you like to start ChatMode now? (y/N): "
if /I "%START_NOW%"=="y" (
    echo.
    call start.bat
) else (
    echo.
    echo You can start ChatMode anytime by running: start.bat
    pause
)
